language: scala

scala:
  - 2.11.11

jdk:
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean test

notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm